export const tools = [
  {
    id: "1",
    title: "Crop Tool",
    icon: "crop",
    color: "#FF69B4",
    requiredTier: "Silver",
  },
  {
    id: "13",
    title: "Scientific Calculator",
    icon: "calculator",
    color: "#3B82F6",
    requiredTier: "Silver",
  },
  {
    id: "14",
    title: "BMI Calculator",
    icon: "heartbeat",
    color: "#F59E0B",
    requiredTier: "Silver",
  },
  {
    id: "2",
    title: "Word Counter",
    icon: "font",
    color: "#10B981",
    requiredTier: "Silver",
  },
  {
    id: "3",
    title: "PDF Scanner",
    icon: "file-pdf",
    color: "#003366",
    requiredTier: "Gold",
  },
  {
    id: "4",
    title: "QR Code Generator",
    icon: "qrcode",
    color: "#8B5CF6",
    requiredTier: "Silver",
  },
  {
    id: "5",
    title: "Notes Pro",
    icon: "sticky-note",
    color: "#EF4444",
    requiredTier: "Silver",
  },
  // ✅ NEW

  // {
  //   id: "6",
  //   title: "Video Trim",
  //   icon: "video",
  //   color: "#EF4444",
  //   requiredTier: "Platinum",
  // },
  {
    id: "7",
    title: "Image Compress",
    icon: "compress-arrows-alt",
    color: "#6366F1",
    requiredTier: "Gold",
  },
  {
    id: "8",
    title: "Translator",
    icon: "language",
    color: "#EC4899",
    requiredTier: "Gold",
  },
  // {
  //   id: "9",
  //   title: "Audio Rec",
  //   icon: "microphone",
  //   color: "#14B8A6",
  //   requiredTier: "Platinum",
  // },
  {
    id: "10",
    title: "Zip Creator",
    icon: "file-archive",
    color: "#F43F5E",
    requiredTier: "Platinum",
  },
  {
    id: "11",
    title: "QR Scanner",
    icon: "qrcode",
    color: "#22C55E",
    requiredTier: "Gold",
  },

  // ✅ NEW
  {
    id: "12",
    title: "Encoder / Decoder",
    icon: "code",
    color: "#0EA5E9",
    requiredTier: "Platinum",
  },

  {
    id: "15",
    title: "Loan Calculator",
    icon: "money-bill-wave",
    color: "#F59E0B",
    requiredTier: "Gold",
  },
  {
    id: "16",
    title: "Tip Calculator",
    icon: "hand-holding-usd",
    color: "#FF8C00",
    requiredTier: "Silver",
  },
  {
    id: "17",
    title: "Currency Converter",
    icon: "exchange-alt",
    color: "#EF4444",
    requiredTier: "Platinum",
  },
  {
    id: "18",
    title: "Unit Converter",
    icon: "ruler-combined",
    color: "#6366F1",
    requiredTier: "Silver",
  },
  {
    id: "19",
    title: "Investment Calc",
    icon: "chart-line",
    color: "#EC4899",
    requiredTier: "Platinum",
  },
  {
    id: "20",
    title: "Discount Calc",
    icon: "percentage",
    color: "#14B8A6",
    requiredTier: "Gold",
  },
  {
    id: "21",
    title: "Fuel Cost Calc",
    icon: "gas-pump",
    color: "#F43F5E",
    requiredTier: "Platinum",
  },
  {
    id: "22",
    title: "Mortgage Calc",
    icon: "home",
    color: "#8B5CF6",
    requiredTier: "Platinum",
  },
  // ✅ NEW TOOLS
  {
    id: "23",
    title: "Algebra Calculator",
    icon: "superscript",
    color: "#7C3AED",
    requiredTier: "Gold",
  },
  {
    id: "24",
    title: "Background Remover",
    icon: "magic",
    color: "#06B6D4",
    requiredTier: "Gold",
  },
  {
    id: "25",
    title: "File Converter",
    icon: "file-export",
    color: "#F97316",
    requiredTier: "Gold",
  },
  {
    id: "26",
    title: "File Compressor",
    icon: "file-archive",
    color: "#84CC16",
    requiredTier: "Gold",
  },
  {
    id: "27",
    title: "PDF Editor",
    icon: "file-signature",
    color: "#DC2626",
    requiredTier: "Platinum",
  },
  {
    id: "28",
    title: "File Editor",
    icon: "file-alt",
    color: "#2563EB",
    requiredTier: "Platinum",
  },
  {
    id: "29",
    title: "Form Fill & Sign",
    icon: "pen-fancy",
    color: "#059669",
    requiredTier: "Platinum",
  },
  {
    id: "30",
    title: "Image Editor",
    icon: "paint-brush",
    color: "#DB2777",
    requiredTier: "Gold",
  },
  {
    id: "31",
    title: "Time Alert",
    icon: "bell",
    color: "#D97706",
    requiredTier: "Silver",
  },
  {
    id: "32",
    title: "Calendar",
    icon: "calendar-alt",
    color: "#0284C7",
    requiredTier: "Silver",
  },
  {
    id: "33",
    title: "Phrasebook",
    icon: "book-open",
    color: "#7C3AED",
    requiredTier: "Gold",
  },
  {
    id: "34",
    title: "Keywords Generator",
    icon: "tags",
    color: "#0D9488",
    requiredTier: "Gold",
  },
  {
    id: "35",
    title: "Boolean Combinator",
    icon: "sitemap",
    color: "#4F46E5",
    requiredTier: "Platinum",
  },
  {
    id: "36",
    title: "Search Tracker",
    icon: "search-plus",
    color: "#B45309",
    requiredTier: "Platinum",
  },
  {
    id: "37",
    title: "AI Detector",
    icon: "robot",
    color: "#6D28D9",
    requiredTier: "Platinum",
  },
  {
    id: "38",
    title: "Plagiarism Checker",
    icon: "shield-alt",
    color: "#047857",
    requiredTier: "Platinum",
  },
];
