export const tools = [
  {
    id: "1",
    title: "Crop Tool",
    icon: "crop",
    color: "#FF69B4",
    requiredTier: "Silver",
  },
  {
    id: "13",
    title: "Scientific Calculator",
    icon: "calculator",
    color: "#3B82F6",
    requiredTier: "Silver",
  },
  {
    id: "14",
    title: "BMI Calculator",
    icon: "heartbeat",
    color: "#F59E0B",
    requiredTier: "Silver",
  },
  {
    id: "2",
    title: "Word Counter",
    icon: "font",
    color: "#10B981",
    requiredTier: "Silver",
  },
  {
    id: "3",
    title: "PDF Scanner",
    icon: "file-pdf",
    color: "#003366",
    requiredTier: "Gold",
  },
  {
    id: "4",
    title: "QR Code Generator",
    icon: "qrcode",
    color: "#8B5CF6",
    requiredTier: "Silver",
  },
  {
    id: "5",
    title: "Notes Pro",
    icon: "sticky-note",
    color: "#EF4444",
    requiredTier: "Silver",
  },
  // ✅ NEW


  // {
  //   id: "6",
  //   title: "Video Trim",
  //   icon: "video",
  //   color: "#EF4444",
  //   requiredTier: "Platinum",
  // },
  {
    id: "7",
    title: "Image Compress",
    icon: "compress-arrows-alt",
    color: "#6366F1",
    requiredTier: "Gold",
  },
  {
    id: "8",
    title: "Translator",
    icon: "language",
    color: "#EC4899",
    requiredTier: "Gold",
  },
  // {
  //   id: "9",
  //   title: "Audio Rec",
  //   icon: "microphone",
  //   color: "#14B8A6",
  //   requiredTier: "Platinum",
  // },
  {
    id: "10",
    title: "Zip Creator",
    icon: "file-archive",
    color: "#F43F5E",
    requiredTier: "Platinum",
  },
  {
    id: "11",
    title: "QR Scanner",
    icon: "qrcode",
    color: "#22C55E",
    requiredTier: "Gold",
  },


  // ✅ NEW
  {
    id: "12",
    title: "Encoder / Decoder",
    icon: "code",
    color: "#0EA5E9",
    requiredTier: "Platinum",
  },

  {
    id: "15",
    title: "Loan Calculator",
    icon: "money-bill-wave",
    color: "#F59E0B",
    requiredTier: "Gold",
  },
  {
    id: "16",
    title: "Tip Calculator",
    icon: "hand-holding-usd",
    color: "#FF8C00",
    requiredTier: "Silver",
  },
  {
    id: "17",
    title: "Currency Converter",
    icon: "exchange-alt",
    color: "#EF4444",
    requiredTier: "Platinum",
  },
  {
    id: "18",
    title: "Unit Converter",
    icon: "ruler-combined",
    color: "#6366F1",
    requiredTier: "Silver",
  },
  {
    id: "19",
    title: "Investment Calc",
    icon: "chart-line",
    color: "#EC4899",
    requiredTier: "Platinum",
  },
  {
    id: "20",
    title: "Discount Calc",
    icon: "percentage",
    color: "#14B8A6",
    requiredTier: "Gold",
  },
  {
    id: "21",
    title: "Fuel Cost Calc",
    icon: "gas-pump",
    color: "#F43F5E",
    requiredTier: "Platinum",
  },
  {
    id: "22",
    title: "Mortgage Calc",
    icon: "home",
    color: "#8B5CF6",
    requiredTier: "Platinum",
  },
];
